const express = require('express');
const cors = require('cors');
const WebSocket = require('ws');
const http = require('http');
const https = require('https');
const { setLatestSensorReading } = require('./runtimeState');
const { getMotorStatus, getPumpStatus } = require('./deviceState');
const apiRoutes = require('./routes/api');

const app = express();
const PORT = process.env.PORT || 7098;
const DOTNET_API_URL = process.env.DOTNET_API_URL || 'https://localhost:7099/api/Data/insert-update';
const FORWARD_TO_DOTNET = process.env.FORWARD_TO_DOTNET !== 'false';

function forwardToDotnet(payload) {
  return new Promise((resolve, reject) => {
    const target = new URL(DOTNET_API_URL);
    const body = JSON.stringify(payload);
    const isHttps = target.protocol === 'https:'; 
    const transport = isHttps ? https : http;

    const req = transport.request(
      {
        protocol: target.protocol,
        hostname: target.hostname,
        port: target.port || (isHttps ? 443 : 80),
        path: `${target.pathname}${target.search}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
        timeout: 5000,
        rejectUnauthorized: false,
      },
      (res) => {
        let responseBody = '';
        res.on('data', (chunk) => {
          responseBody += chunk.toString();
        });
        res.on('end', () => {
          resolve({ status: res.statusCode, body: responseBody });
        });
      }
    );

    req.on('error', reject);
    req.on('timeout', () => req.destroy(new Error('Dotnet API request timeout')));
    req.write(body);
    req.end();
  });
}

// ═══════════════════════════════════════════════════════
// DUMMY DATA GENERATOR - Always Active
// Simulates ESP32 Sensor Data and sends to .NET API
// Sends whether ESP32 is connected or not
// ═══════════════════════════════════════════════════════
const DUMMY_DATA_ENABLED = process.env.DUMMY_DATA !== 'false';

// Track cycle progress for realistic simulation
let cycleProgressCounter = 0;
let waterUsedTotal = 0;
let energyUsedTotal = 0;
let sensorId = 1;

function generateDummyData() {
  // Increment cycle progress (0-100%) - increments by 2-5% each cycle
  cycleProgressCounter = Math.min(100, cycleProgressCounter + Math.random() * 3 + 2);
  
  // Reset cycle when complete
  if (cycleProgressCounter >= 100) {
    cycleProgressCounter = 0;
  }

  // Accumulate water and energy usage
  const waterThisCycle = parseFloat((Math.random() * 2 + 1).toFixed(2));  // 1-3 liters per reading
  const energyThisCycle = parseFloat((Math.random() * 0.05 + 0.02).toFixed(3)); // 0.02-0.07 kWh per reading
  
  waterUsedTotal += waterThisCycle;
  energyUsedTotal += energyThisCycle;

  // Convert status values to strings ('on'/'off') for .NET API
  const pumpStatusValue = getPumpStatus();
  const motorStatusValue = getMotorStatus();
  const pumpStatusString = (pumpStatusValue === 1 || pumpStatusValue === true || pumpStatusValue === 'on') ? 'on' : 'off';
  const motorStatusString = (motorStatusValue === 1 || motorStatusValue === true || motorStatusValue === 'on') ? 'on' : 'off';

  // Format data to match DataModel
  // NOTE: Don't send sensor_id - let SQL Server auto-increment it via IDENTITY
  return {
    weight: parseFloat((Math.random() * 15 + 40).toFixed(2)),              // 40-55 kg
    load_weight: parseFloat((Math.random() * 2 + 1).toFixed(2)),           // 1-3 kg
    water_level: parseFloat((Math.random() * 60 + 40).toFixed(2)),         // 40-100%
    turbidity: parseFloat((Math.random() * 5 + 5).toFixed(2)),             // 5-10 NTU
    current_value: parseFloat((Math.random() * 3 + 1).toFixed(2)),         // 1-4 Amperes
    hx711_ready: true,
    pump_status: pumpStatusString,                                          // 'on' or 'off'
    motor_status: motorStatusString,                                        // 'on' or 'off'
    // created_time is auto-generated by SQL Server via GETDATE()
  };
}

async function sendDummyDataToDataEndpoint() {
  if (!DUMMY_DATA_ENABLED) return;

  const dummyData = generateDummyData();
  
  // Store in runtime state for frontend to fetch
  setLatestSensorReading(dummyData);

  // Send ONLY to /Data/insert-update endpoint
  const endpoint = 'https://localhost:7099/api/Data/insert-update';

  try {
    const target = new URL(endpoint);
    const body = JSON.stringify(dummyData);
    const isHttps = target.protocol === 'https:';
    const transport = isHttps ? https : http;

    const req = transport.request(
      {
        protocol: target.protocol,
        hostname: target.hostname,
        port: target.port || (isHttps ? 443 : 80),
        path: `${target.pathname}${target.search}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
        timeout: 5000,
        rejectUnauthorized: false,
      },
      (res) => {
        let responseBody = '';
        res.on('data', (chunk) => {
          responseBody += chunk.toString();
        });
        res.on('end', () => {
          console.log(`[DUMMY-DATA] Sent to /Data/insert-update (Status: ${res.statusCode})`);
          if (res.statusCode !== 200 && res.statusCode !== 201) {
            console.warn(`[DUMMY-DATA] Warning: Status ${res.statusCode}. Response: ${responseBody}`);
          }
        });
      }
    );

    req.on('error', (err) => {
      console.error(`[DUMMY-DATA] Failed to send to /Data/insert-update: ${err.message}`);
    });

    req.on('timeout', () => req.destroy(new Error('Request timeout')));
    req.write(body);
    req.end();
  } catch (err) {
    console.error(`[DUMMY-DATA] Error sending to ${endpoint}:`, err.message);
  }
}

// Start dummy data generator (only when ESP32 is NOT connected)
let dummyDataInterval = null;

if (DUMMY_DATA_ENABLED) {
  dummyDataInterval = setInterval(() => {
    if (!esp32Connected) {
      sendDummyDataToDataEndpoint();
    }
  }, 2000);
  console.log('[DUMMY-DATA] Generator started - will send every 2 seconds when ESP32 is NOT connected');
}

// ═══ Middleware ═══
app.use(cors());
app.use(express.json());

// Request logging middleware
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`);
  next();
});

// ═══ Simple Health Check ═══
app.get('/ping', (req, res) => {
  console.log('Ping endpoint called');
  res.json({ status: 'pong', timestamp: new Date().toISOString() });
});

// ═══ API Routes ═══
app.use('/api', apiRoutes);

// ═══ Health check ═══
app.get('/', (req, res) => {
  res.json({ 
    status: 'Smart Washer Backend is running',
    timestamp: new Date().toISOString(),
    port: PORT,
    api: `/api`,
    sqlServer: 'Connected via .NET API',
    dotnetEndpoint: DOTNET_API_URL,
    healthy: true
  });
});

// ═══════════════════════════════════════════════════════
// ESP32 WebSocket Client
// Connects to ESP32 WebSocket and stores incoming data
// ═══════════════════════════════════════════════════════
let esp32Ws = null;
let esp32Ip = null;
let esp32Connected = false; // Track connection status
let reconnectTimer = null;
let reconnectAttempts = 0;
let lastError = null;
let lastErrorTime = null;

let esp32ConnectionStartTime = null;

function connectToESP32(ip) {
  if (esp32Ws) {
    try { esp32Ws.close(); } catch {}
  }
  clearTimeout(reconnectTimer);

  esp32Ip = ip;
  const url = `ws://${ip}:81`;
  esp32ConnectionStartTime = Date.now();
  reconnectAttempts++;
  
  // Only log every 3rd attempt to reduce spam
  if (reconnectAttempts % 3 === 1) {
    console.log(`[ESP32-Bridge] Connecting to ${url}... (attempt ${reconnectAttempts})`);
  }

  esp32Ws = new WebSocket(url);

  // Timeout handler - fail if no connection after 10 seconds
  const connectionTimeout = setTimeout(() => {
    if (esp32Ws && esp32Ws.readyState !== WebSocket.OPEN) {
      console.error(`[ESP32-Bridge] ✗ Connection timeout: Unable to connect to ${url}`);
      try { esp32Ws.close(); } catch {}
      esp32Ws = null;
    }
  }, 10000);

  esp32Ws.on('open', () => {
    clearTimeout(connectionTimeout);
    esp32Connected = true; // Mark as connected
    const elapsed = Date.now() - esp32ConnectionStartTime;
    console.log(`[ESP32-Bridge] ✓ Connected to ESP32 at ${ip} (took ${elapsed}ms)`);
  });

  esp32Ws.on('message', async (raw) => {
    try {
      const data = JSON.parse(raw.toString());
      setLatestSensorReading({
        weight: data.weight ?? null,
        load_weight: data.load_weight ?? null,
        water_level: data.water_level ?? null,
        turbidity: data.turbidity ?? null,
        current: data.current ?? 0,
        hx711_ready: data.hx711_ready ?? null,
        pump_status: data.pump_status ?? null,
        motor_status: data.motor_status ?? null,
        temperature: data.temperature ?? null,
      });
      // All data is forwarded to SQL Server via .NET API

      if (FORWARD_TO_DOTNET) {
        // Convert to DataModel format for .NET API
        const pumpStatusStr = (data.pump_status === 1 || data.pump_status === true || data.pump_status === 'on') ? 'on' : 'off';
        const motorStatusStr = (data.motor_status === 1 || data.motor_status === true || data.motor_status === 'on') ? 'on' : 'off';
        
        const dataForDotnet = {
          sensor_id: 1,
          weight: data.weight ?? 0,
          load_weight: data.load_weight ?? 0,
          water_level: data.water_level ?? 0,
          turbidity: data.turbidity ?? 0,
          current_value: data.current ?? 0,
          hx711_ready: data.hx711_ready ?? true,
          pump_status: pumpStatusStr,
          motor_status: motorStatusStr,
          // created_time is auto-generated by SQL Server
        };
        const dotnetResult = await forwardToDotnet(dataForDotnet);
        console.log(`[DOTNET] Forwarded ESP32 reading (${dotnetResult.status}) to ${DOTNET_API_URL}`);
      }

      console.log(`[ESP32] Reading received — water:${data.water_level}% load:${data.load_weight}kg current:${data.current}A temp:${data.temperature}°C pump:${data.pump_status} motor:${data.motor_status}`);
    } catch (err) {
      console.error('[ESP32] Error handling sensor data:', err.message);
    }
  });

  esp32Ws.on('close', () => {
    esp32Connected = false; // Mark as disconnected
    console.log('[ESP32-Bridge] Connection closed');
    esp32Ws = null;
    // Auto-reconnect after 5 seconds
    if (esp32Ip) {
      reconnectTimer = setTimeout(() => connectToESP32(esp32Ip), 5000);
    }
  });

  esp32Ws.on('error', (err) => {
    clearTimeout(connectionTimeout);
    lastError = err.message;
    lastErrorTime = new Date().toISOString();
    
    // Only log unique errors (not repeats)
    if (err.message !== lastError) {
      console.error(`[ESP32-Bridge] ✗ Error (attempt ${reconnectAttempts}): ${err.message}`);
      
      if (err.message.includes('ECONNREFUSED')) {
        console.error(`  Port 81 is CLOSED or NOT LISTENING at ${ip}`);
        console.error(`  → ESP32 WebSocket server is NOT running`);
        console.error(`  → Check: Is ESP32 powered? Is firmware running? Is port 81 correct?`);
      } else if (err.message.includes('ETIMEDOUT')) {
        console.error(`  Connection TIMED OUT (10s) - IP may be unreachable`);
        console.error(`  → Check: Can you ping ${ip}?`);
        console.error(`  → Verify: Same network? Firewall blocking port 81?`);
      } else if (err.message.includes('EHOSTUNREACH')) {
        console.error(`  Host UNREACHABLE - cannot reach ${ip}`);
        console.error(`  → Verify IP address is correct`);
        console.error(`  → Check: Same WiFi network?`);
      } else {
        console.error(`  Cannot connect to ws://${ip}:81`);
        console.error(`  1. Verify ESP32 IP address: ${ip}`);
        console.error(`  2. Ensure WebSocket server runs on port 81`);
        console.error(`  3. Check network connectivity`);
      }
    }
  });
}

app.post('/api/esp32/connect', (req, res) => {
  const { ip } = req.body;
  if (!ip) {
    return res.status(400).json({ success: false, error: 'IP address is required' });
  }
  // Validate IP format (basic check)
  const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$|^localhost$/i;
  if (!ipRegex.test(ip)) {
    return res.status(400).json({ success: false, error: 'Invalid IP address format' });
  }
  connectToESP32(ip);
  res.json({ success: true, message: `Connecting to ESP32 at ${ip}...` });
});

// ═══ Endpoint to disconnect backend from ESP32 ═══
app.post('/api/esp32/disconnect', (req, res) => {
  clearTimeout(reconnectTimer);
  esp32Ip = null;
  esp32Connected = false; // Mark as disconnected
  if (esp32Ws) {
    try { esp32Ws.close(); } catch {}
    esp32Ws = null;
  }
  res.json({ success: true, message: 'Disconnected from ESP32' });
});

// ═══ Endpoint to check ESP32 connection status ═══
app.get('/api/esp32/status', (req, res) => {
  res.json({
    connected: esp32Connected,
    esp32Ip: esp32Ip,
    dummyDataActive: !esp32Connected,
    message: esp32Connected 
      ? `✓ ESP32 connected at ${esp32Ip} - Using real sensor data`
      : 'Using dummy data - ESP32 not connected'
  });
});


// ═══ Endpoint to check ESP32 bridge status ═══
app.get('/api/esp32/status', (req, res) => {
  res.json({
    connected: esp32Ws !== null && esp32Ws.readyState === WebSocket.OPEN,
    ip: esp32Ip,
    reconnectAttempts: reconnectAttempts,
    lastError: lastError,
    lastErrorTime: lastErrorTime,
  });
});

// ═══ Diagnostic endpoint - Check all system status ═══
app.get('/api/system/status', (req, res) => {
  const errorDetails = lastError ? {
    error: lastError,
    time: lastErrorTime,
    attempts: reconnectAttempts,
  } : null;

  res.json({
    timestamp: new Date().toISOString(),
    backend: {
      running: true,
      port: PORT,
      uptime: process.uptime(),
    },
    database: {
      connected: true,
      type: 'SQL Server',
      method: '.NET API',
      endpoint: DOTNET_API_URL,
      message: 'Using SQL Server via .NET API',
    },
    esp32: {
      connected: esp32Connected,
      ip: esp32Ip,
      port: 81,
      reconnectAttempts: reconnectAttempts,
      errorDetails: errorDetails,
      message: !esp32Connected 
        ? 'Not connected - Using dummy data'
        : `✓ Connected to ${esp32Ip}:81 - Using real sensor data`,
    },
    dotnet: {
      forwardingEnabled: FORWARD_TO_DOTNET,
      url: FORWARD_TO_DOTNET ? DOTNET_API_URL : 'disabled',
    },
  });
});

// ═══ Start Server ═══
async function startServer() {
  const server = app.listen(PORT, () => {
    console.log(`\n🚀 Smart Washer Backend running on http://localhost:${PORT}`);
    console.log(`   API endpoints available at http://localhost:${PORT}/api`);
    console.log(`   Forwarding ESP32 data to SQL Server via .NET API`);
    console.log(`   Endpoint: ${DOTNET_API_URL}`);
    console.log(`\n   To start ESP32 bridge, POST to /api/esp32/connect with { "ip": "ESP32_IP" }\n`);
  });

  // Error handling
  server.on('error', (err) => {
    console.error('[Server Error]', err);
  });

  process.on('uncaughtException', (err) => {
    console.error('[Uncaught Exception]', err);
  });

  process.on('unhandledRejection', (reason, promise) => {
    console.error('[Unhandled Rejection]', reason);
  });
}

startServer().catch((err) => {
  console.error('[Startup Error]', err);
  process.exit(1);
});
